name: Android CI

on:
  workflow_dispatch:
      inputs:
        version:
          description: 'Application version'     
          required: true
          default: '1.0'
jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build APK
      run: ./gradlew :app:assembleRelease
    - name: Upload APK
      uses: actions/upload-artifact@v3.1.2
      with:
        name: addressbook
        path: app/build/outputs/apk/release/Addressbook_${{ github.event.inputs.version }}.apk
  release:
      name: Release APK
      needs: build
      runs-on: ubuntu-latest
      steps:
        - name: Download APK from build
          uses: actions/download-artifact@v1
          with:
            name: addressbook 
        - name: Create Release
          id: create_release
          uses: softprops/action-gh-release@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
          with:
            tag_name: v${{ github.event.inputs.version }}
            name: Release v${{ github.event.inputs.version }}
            draft: false
            prerelease: false
            files: addressbook/Addressbook_${{ github.event.inputs.version }}.apk
